#!/bin/bash
# DEFAULT_INSTALLATION_MODE=N

# Common
DEFAULT_BASIC_SETUP=N
# HOSTNAME=
# USERNAME=
# TIMEOUT=
DEFAULT_YUM_UPDATE=N
DEFAULT_YUM_UPGRADE=N
DEFAULT_COMMON_LIBRARY=N
DEFAULT_INSTALLATION_PATH=/usr/local

# Docker
DEFAULT_DOCKER=N
DEFAULT_DOCKER_VERSION=18.09.9
DEFAULT_DOCKER_COMPOSE=Y
DEFAULT_DOCKER_COMPOSE_VERSION=1.25.0-rc2
DEFAULT_DOCKER_INSTALLATION_SOURCE=0

# Kubernetes
DEFAULT_KUBERNETES=N
DEFAULT_KUBERNETES_INSTALLATION_SOURCE=0

# Helm
DEFAULT_HELM=N
DEFAULT_HELM_OVERWRITE=N
DEFAULT_HELM_VERSION=2.14.3

# Git
DEFAULT_GIT=N
DEFAULT_GIT_REPOSITORY=N
DEFAULT_GIT_REPOSITORY_USERNAME=git

# Ruby
DEFAULT_RUBY=N
DEFAULT_RUBY_OVERWRITE=N
DEFAULT_RUBY_VERSION=2.6.4

# Nginx
DEFAULT_NGINX=N
DEFAULT_NGINX_OVERWRITE=N
DEFAULT_NGINX_VERSION=1.16.1
DEFAULT_NGINX_WITH_PASSENGER=N

# Passenger
DEFAULT_PASSENGER=N
DEFAULT_PASSENGER_OVERWRITE=N
DEFAULT_PASSENGER_VERSION=6.0.2

# Node
DEFAULT_NODE=N
DEFAULT_NODE_OVERWRITE=N
DEFAULT_NODE_VERSION=10.16.3

# Python3
DEFAULT_PYTHON3=N
DEFAULT_PYTHON3_OVERWRITE=N
DEFAULT_PYTHON3_VERSION=3.7.4
