#!/bin/bash

# Common
DEFAULT_BASIC_SETUP=N
# HOSTNAME=
# USERNAME=
# TIMEOUT=
DEFAULT_COMMON_LIBRARY=N
DEFAULT_INSTALLATION_PATH=/usr/local
DEFAULT_YUM_UPDATE=N
DEFAULT_YUM_UPGRADE=N

# Bind
DEFAULT_BIND=N
DEFAULT_BIND_OVERWRITE=N
DEFAULT_BIND_VERSION=9.11.5-P1

# Docker
DEFAULT_DOCKER=N
DEFAULT_DOCKER_COMPOSE=Y
DEFAULT_DOCKER_COMPOSE_VERSION=1.23.2

# Git
DEFAULT_GIT=N
DEFAULT_GIT_REPOSITORY=N
DEFAULT_GIT_REPOSITORY_USERNAME=git

# Ruby
DEFAULT_RUBY=N
DEFAULT_RUBY_OVERWRITE=N
DEFAULT_RUBY_VERSION=2.5.3

# Nginx
DEFAULT_NGINX=N
DEFAULT_NGINX_OVERWRITE=N
DEFAULT_NGINX_VERSION=1.14.2
DEFAULT_NGINX_WITH_PASSENGER=N
DEFAULT_NODE_VERSION=10.14.1

# Passenger
DEFAULT_PASSENGER=N
DEFAULT_PASSENGER_OVERWRITE=N
DEFAULT_PASSENGER_VERSION=6.0.0

# Node
DEFAULT_NODE=N
DEFAULT_NODE_OVERWRITE=N

# Python3
DEFAULT_PYTHON3=N
DEFAULT_PYTHON3_OVERWRITE=N
DEFAULT_PYTHON3_VERSION=3.7.1
